package ru.ilka.logic;

/**
 * Here could be your advertisement +375 29 3880490
 */
public enum LogicResult {
    OK,
    BANNED,
    EMAIL_UNUNIQUE,
    LOGIN_UNUNIQUE,
    REGISTER_INVITE_WRONG,
    FAILED,
    WRONG_NAME,
    UNAVALIABLE_CARD,
    INVALID_PASSWORD,
    INVALID_EMAIL,
    INVALID_LOGIN,

    CARD_2_H, //hearts
    CARD_2_C, //clubs
    CARD_2_D, //diamonds
    CARD_2_S, //spades
    CARD_3_H,
    CARD_3_C,
    CARD_3_D,
    CARD_3_S,
    CARD_4_H,
    CARD_4_C,
    CARD_4_D,
    CARD_4_S,
    CARD_5_H,
    CARD_5_C,
    CARD_5_D,
    CARD_5_S,
    CARD_6_H,
    CARD_6_C,
    CARD_6_D,
    CARD_6_S,
    CARD_7_H,
    CARD_7_C,
    CARD_7_D,
    CARD_7_S,
    CARD_8_H,
    CARD_8_C,
    CARD_8_D,
    CARD_8_S,
    CARD_9_H,
    CARD_9_C,
    CARD_9_D,
    CARD_9_S,
    CARD_10_H,
    CARD_10_C,
    CARD_10_D,
    CARD_10_S,
    CARD_J_H,
    CARD_J_C,
    CARD_J_D,
    CARD_J_S,
    CARD_Q_H,
    CARD_Q_C,
    CARD_Q_D,
    CARD_Q_S,
    CARD_K_H,
    CARD_K_C,
    CARD_K_D,
    CARD_K_S,
    CARD_A_H,
    CARD_A_C,
    CARD_A_D,
    CARD_A_S;
}
